### PR TITLE
undebate-ssp send password#154

### PR DESCRIPTION
**Pull request by ice1080**

### CODE REVIEW

**Comment by ddfridley** [comment]
One thing, we can't use mixed case file names - because the people at mICROsOFT decided to ignore case, which cause problems.  I recommend this convention for all open source projects.   I can work with it as is, and my just make the changes and commit them if you are on vacation. (Have a good vacation).

**Comment by ddfridley** [comment]
I realize some of them were already mixed case - but I have been burned by this recently. I'll fix it.

**Comment by ice1080** [comment]
Sorry, which files are incorrect? I can fix them today. Unfortunately macOS also ignores case, and it's really only linux that is fully case sensitive with files.

**Comment by ddfridley** [comment]
several in app/components/auth-form/  - resetPassword is the new one, but might as well fix the others too.

Storybook is interesting, when I run it, it has something that complains about case. But even git (on windows anyway) doesn't track the difference between Footer.js and footer.js

Also, if you do a new commit, run npm install first so that the new version number in package.json gets updated in package-lock.json

**Comment by ice1080** [comment]
Sounds good. Are you fixing them or am I?
And sorry about that, I thought I had included the updated package-lock.json, but that must have only been in civil-server.

**Pull request merged**
